@startmindmap
* Значимые\nнефункциональные\nтребования
**[#Orange] Эргономичность
***_ Независимая оптимизация интерфейса для
****_ ПК
****_ сенсорного экрана
****_ широкого экрана
***_ Темп игры, время хода персонажа
****_ не более 30 секунд в среднем
***_ Время создания игрового объекта
****_ не более 30 секунд во время игры
****_ не более 2 минут до игры
***_ Отзывы пользователей
**[#Orange] Доступность
***_ Необработка запросов
****_ менее 5 секунд за час (0,15%)
**[#Orange] Отказоустойчивость
***_ Среднее время хода персонажа за проблемный период
****_ не меняется более, чем на 30%
***_ Количество игровых сессий за проблемный период + 4 часа
****_ не меняется более, чем на 30%
***_ Отзывы пользователей за проблемные периоды
**[#Orange] Отзывчивость
***_ Время обработки запроса
****_ Поиск по компендиуму
*****_ менее 1 секунды
****_ Действие персонажа
*****_ менее 1 секунды
****_ Опрос изменений в окружении
*****_ менее 2 секунд
****_ Время генерации порции подсказок
*****_ менее 5 секунд
***_ Отзывы пользователей
**[#Orange] Производительность
***_ Количество одновременно играющих кампаний
****_ до 50
***_ Количество пользователей, активно шлющих запросы
****_ до 300
***_ Количество запросов в секунду
****_ до 60
***_ Отзывы пользователей
** Сопровождаемость
***_ Время диагностики проблемы
****_ до 10 минут
***_ Время формирования постановки для фикса
****_ до 10 минут
***_ Процент постановок, созданных автоматически
****_ до 50%
** Совместимость
***_ Процент охвата экспорта из сторонней системы
****_ более 95%
***_ Процент охвата экспорта из выбранных сторонних систем
****_ более 95%
@endmindmap
