@startmindmap
<style>
node{
    :depth(2) {
        MaximumWidth 500
        LineColor none
        RoundCorner 0
        Padding 2
        Margin 2
    }
    :depth(3) {
        MaximumWidth 500
        LineColor none
        RoundCorner 0
        Padding 2
        Margin 2
    }
}
</style>
* Функциональные\nтребования
** До игры
*** аутентификация через внешний сервис
*** поиск компании для прохождения
*** импорт персонажей из других платформ
*** экспорт персонажей, прохождения (все персонажи), журнала (один персонаж)
*** обучение начинающих
*** инструменты для создания и редактирования
**** кампании
**** карты
**** персонажей
**** предметов
**** сюжета
*** импорт/экспорт контента
** Для игры
*** листы персонажа
*** карта местности
*** инструменты для управления персонажем
*** чат кампании для участников
**** текст
**** смайлики
**** стикеры (картинки с эмоциями или мемами)
**** реакции на сообщения
**** голосовое общение в реальном времени
*** звуковые эффекты и музыка
*** подсказки ведущему
**** типичные реакции игрового мира на действия игроков
**** моделирование характера и поведения персонажей
**** настройка под свой стиль ведения игры
**** имитацию стиля определенного ДМ
*** генератор/конструктор игровых объектов
*** модуль с правилами D&D 5
*** модуль с правилами Pathfinder 2
@endmindmap
