@startmindmap
<style>
leafNode {
    MaximumWidth 500
    LineColor none
    RoundCorner 0
    Padding 2
    Margin 2
}
</style>
* Ограничения

** Регуляторные
*** Лицензирование Pathfinder 2 - Open Game License 1.0. Royalty-free.
*** Лицензирование Dungeon & Dragons 5 - Open Game License 1.0. Требует отчислений 25% от прибыли от использования лицензируемого контента при достижении годовой прибыли в 750 тысяч долларов.;

** Ресурсные
*** У команды максимум 5 участников (разработчики, сопровождение).
*** Бюджет ограничен 3 млн. руб.
*** Время на разработку системы - до 2 лет.

** Технологические
*** Стек ограничен известными стартовой команде технологиями и крайне нежелательно уходить от него.
*** Продукт должен быть способен развернуться на linux-серверах

** Организационные
*** Разработка должна вестись с помощью гибких методологий с визуализацией прогресса.
*** Раз в 2 недели должна проходить встреча разработки и заказчика для демонстрации результата заказчику и определением вектора усилий на следующий этап.

** Бизнес
*** Игроки из одной игровой комнаты обычно из одного или соседних часовых поясов.
*** Игроки из одного региона обычно начинают и заканчивают играть в сходные интервалы времени.
@enduml
