@startuml
!include  https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Диаграмма контекста для движка игр основанных на d20
HIDE_STEREOTYPE()
LAYOUT_LEFT_RIGHT()

Person_Ext(owner, "Владелец", "")
Person_Ext(cm, "Автор", "")
Person_Ext(dm, "ДМ", "(Ведущий)")
Person_Ext(player, "Игрок", "")
Person_Ext(table, "Игровой стол", "")

System(d20platform, "Платформа для игр, основанных на d20", "Помогает ДМ-у вести игры")

System_Ext(oauth, "OAuth2 провайдеры", "")
System_Ext(discord, "Discord", "")

Rel(owner, d20platform, "Управляет системой")
Rel(cm, d20platform, "Наполняет контентом")
Rel(dm, d20platform, "Ведет игру")
Rel(player, d20platform, "Играет")
Rel_Back(table, d20platform, "Отображает информацию всем игрокам")

Rel(d20platform, oauth, "Аутентифицирует")
Rel(d20platform, discord, "Воспроизводит музыку и эффекты, транслирует события игрового мира")
@enduml
