@startuml
actor "Пользователи" as users

node "srv1" {
    portin pi1

    rectangle "контейнер nginx" {
        portin ni1
        portout no1
        component "API Gateway" as gateway
        storage "Кеш" as cache
        ni1-gateway
        gateway-no1
        gateway-le-cache
    }
    rectangle "контейнер сервиса\n[1..2]" {
        portin si1
        component "Сервис" as service
        portout so1
        portout so2
        portout so3
        portout so4
        portout so5
        si1-service
        service-so1
        service-so2
        service-so3
        service-so4
    }
    rectangle "контейнер БД" {
        portin di1
        database "БД мастер" as db
        di1-db
    }

    rectangle "контейнер очереди" {
            port q1
            queue "Очередь" as coreQueue
            q1 - coreQueue
        }

    rectangle "контейнер подсказок\n[1..2]" {
        portin hi1
        component "Модуль подсказок" as hint
        database "БД подсказок" as hintDb
        hi1-hint
        hintDb-hint
    }
    pi1--ni1
    no1--si1
    so1--di1
    so2--hi1
    so5--q1
}
cloud "OAuth2-сервис" as oauth2
cloud "Discord API" as discord

node "srv2" {
    portin ri1
    database "БД реплика" as replica
    ri1-replica
}
users--pi1
so3--oauth2
so4--discord
ri1--di1
@enduml
