@startuml
left to right direction
actor "Интерфейс\nвладельца" as IO
actor "Интерфейс\nредактора" as IE
actor "Интерфейс\nигрока" as IP
actor "Интерфейс\nведущего" as ID
cloud "Discord"
cloud "OAuth2-провайдер"
note right of "Discord": текстовый и голосовой каналы на сервере
note right of "OAuth2-провайдер": внешний сервис аутентификации

package "Обучение" {
    [Редактирование обучения]
    [Обучение редактора]
    [Обучение игрока]
    [Обучение ведущего]
}
package "Пользователи" {
    [Аутентификация]
    [Управление пользователями]
}
package "Игровые комнаты" {
    [Создание комнаты]
    [Поиск комнат]
    [Присоединение к комнате]
    [Выход из комнаты]
    [Архивирование комнаты]
}

package "Книги: базовые, сеттинга, приключений, хоумбрю" {
    [Создание игрового объекта]
    [Редактирование игрового объекта]
    [Удаление игрового объекта]
    [Получение игрового объекта]
    [Поиск списка игровых объектов]
}

package "Прохождение" {
    [Создание прохождения]
    [Генерация игрового объекта]
    [Изменение игрового объекта]
    [Запись об изменении игрового объекта]
    [Получение записей об игровом объекте]
    [Получение состояния списка игровых объектов]
}

package "Подсказки" {
    [Запрос подсказок]
    [Настройка подсказок]
}

database "Пользователи, права,\nигровые комнаты,\nобучающие материалы"
database "Обучающие материалы"
note "Объекты со свойствами,\nпоиск, фильтрация,\nобъединение" as bookDb
database "D&D 5"
"D&D 5"..bookDb
database "Pathfinder 2"
"Pathfinder 2"..bookDb

database "Карты, объекты на карте"
note right: файлы,\nразмеры до 1Мб
database "Хроника"
note right: все игровые события,\nмного деталей,\nмного записей
database "Данные прохождения"
note right: патч хроники\nпо каждому\nпрохождению
database "Данные подсказок"
note right: Итоговые шаблоны сообщений

"Обучение" --> "Обучающие материалы"
@enduml
