@startmindmap
* Функциональные\nтребования
**_ Пользователю\nдо игры
***_ аутентификация через внешний сервис
***_ поиск компании для прохождения
***_ импорт персонажей из других платформ
***_ экспорт персонажей, прохождения (все персонажи), журнала (один персонаж)
**_ Ведущему\nдо игры
***_ инструменты для создания и редактирования
****_ кампании
****_ карты
****_ персонажей
****_ предметов
****_ сюжета
***_ импорт/экспорт контента
**_ Игроку\nдля игры
***_ листы персонажа
***_ карта местности
***_ обучение начинающих
***_ инструменты для управления персонажем
***_ чат кампании для участников
****_ текст
****_ смайлики
****_ стикеры (картинки с эмоциями или мемами)
****_ реакции на сообщения
****_ голосовое общение в реальном времени
***_ звуковые эффекты и музыка
**_ Ведущему\nдля игры
***_ подсказки ведущему
****_ типичные реакции игрового мира на действия игроков
****_ моделирование характера и поведения персонажей
****_ настройка под свой стиль ведения игры
****_ имитацию стиля определенного ДМ
***_ генератор/конструктор игровых объектов
***_ модуль с правилами D&D 5
***_ модуль с правилами Pathfinder 2
@endmindmap
