@startmindmap
* Значимые\nнефункциональные\nтребования
** Эргономичность
***_ Темп игры, время хода персонажа
****_ не более 30 секунд в среднем
***_ Время создания игрового объекта
****_ не более 30 секунд во время игры
****_ не более 2 минут до игры
***_ Отзывы пользователей
** Доступность
***_ Процент необработанных запросов
****_ менее 1%
** Отказоустойчивость
***_ Среднее время хода персонажа при отказе модуля
****_ не меняется более, чем на 30%
***_ Отзывы пользователей за проблемные периоды
** Отзывчивость
***_ Время обработки запроса
****_ Поиск по компендиуму
*****_ менее 1 секунды
****_ Действие персонажа
*****_ менее 1 секунды
****_ Опрос изменений в окружении
*****_ менее 2 секунд
****_ Время генерации порции подсказок
*****_ менее 5 секунд
***_ Отзывы пользователей
** Производительность
***_ Количество одновременно играющих кампаний
****_ до 50
***_ Количество запросов в секунду
****_ до 20
***_ Отзывы пользователей
** Сопровождаемость
***_ Время диагностики проблемы
****_ до 10 минут
***_ Время формирования постановки для фикса
****_ до 10 минут
***_ Процент постановок, созданных автоматически
****_ до 50%
** Совместимость
***_ Процент охвата экспорта из сторонней системы
****_ более 95%
***_ Процент охвата экспорта из выбранных сторонних систем
****_ более 95%
@endmindmap
