@startuml
left to right direction

actor "Владелец" as UO $UO #blue;line:blue;line.bold;text:blue
actor "Редактор" as UE $UE #maroon;line:maroon;line.bold;text:maroon
actor "Игрок" as UP $UP #orange;line:orange;line.bold;text:orange
actor "Ведущий" as UD $UD #green;line:green;line.bold;text:green

rectangle "Пользователи" as Users {
    usecase "Регистрироваться" as Register
    usecase "Аутентифицироваться" as Auth
    usecase "Управлять пользователями" as ManageUsers
    usecase "Выходить из системы" as Logout
    UP --> Register #orange
    UO --> Auth #blue
    UE --> Auth #maroon
    UP --> Auth #orange
    UD --> Auth #green
    UO --> ManageUsers #blue
    UO --> Logout #blue
    UE --> Logout #maroon
    UP --> Logout #orange
    UD --> Logout #green

}

rectangle "Игровые комнаты" as Rooms {
    usecase "Управлять игровыми комнатами" as ManageRoom
    usecase "Искать игровые комнаты" as SearchRoom
    usecase "Вступать в игровую комнату" as JoinRoom
    usecase "Покидать игровую комнату" as LeaveRoom
    UD --> ManageRoom #green
    UP --> SearchRoom #orange
    UP --> JoinRoom #orange
    UP --> LeaveRoom #orange
}

rectangle "Обучение" as Education {
    usecase "Проходить обучение" as Learn
    usecase "Редактировать обучение" as EditLearn
    UP --> LeaveRoom #orange
    UE --> Learn #maroon
    UE --> EditLearn #maroon
    UP --> Learn #orange
    UD --> Learn #green
}

rectangle "Контент книг, сеттингов, приключений, хоумбрю" as Content {
    usecase "Получать контент" as ReadContent #red
    usecase "Редактировать контент" as EditContent
    UE --> ReadContent #maroon
    UE --> EditContent #maroon
    UP --> ReadContent #orange
    UD --> ReadContent #green
}

rectangle "Данные прохождения" as Campaigns {
    usecase "Получать состояние объекта" as GetState #red
    usecase "Менять состояние объекта" as ChangeState #red
    usecase "Генерировать игровые объекты" as Generate #red
    usecase "Импортировать персонажа" as ImportChar
    usecase "Экспортировать персонажа" as ExportChar
    usecase "Экспортировать прохождение" as ExportHistory
    UP --> GetState #orange
    UP --> ChangeState #orange
    UP --> ImportChar #orange
    UP --> ExportChar #orange
    UD --> Generate #green
    UD --> GetState #green
    UD --> ChangeState #green
    UD --> ExportHistory #green
}

rectangle "Подсказки" as Hints {
    usecase "Запрашивать подсказки" as AskHint #red
    usecase "Настраивать подсказки" as TuneHint
    UD --> AskHint #green
    UD --> TuneHint #green
}

'remove Hints
'remove Users
'remove Education
'remove Rooms
'remove UO
'remove UE
remove @unlinked
@enduml
