@startuml
package "Игровые комнаты" as Room {
    rectangle "Создавать игровую комнату"
    rectangle "Редактировать игровую комнату"
    rectangle "Архивировать игровую комнату"
    rectangle "Искать игровые комнаты"
    rectangle "Вступать в игровую комнату"
    rectangle "Покидать игровую комнату"
}
@enduml
