@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Диаграмма компонентов для движка игр основанных на d20
HIDE_STEREOTYPE()
LAYOUT_LEFT_RIGHT()

Person_Ext(cm, "Автор", "")
Person_Ext(dm, "ДМ", "(Ведущий)")
Person_Ext(owner, "Владелец", "")
Person_Ext(player, "Игрок", "")
Person_Ext(table, "Игровой стол", "")
System_Ext(oauth, "OAuth2 провайдеры", "")
System_Ext(discord, "Discord API", "")

AddRelTag("external", $lineColor="pink")
AddRelTag("dm", $lineColor="green")
AddRelTag("player", $lineColor="orange")

System_Boundary(d20platform, "Платформа") {
    Container(gateway, "API Gateway")
    ContainerDb(cache, "Кеш", "fs, webDav", "")

    Container_Boundary(queue, "Контейнер очереди"){
        ComponentQueue(eventQueue, "Очередь необработанных действий при игре")
        ComponentQueue(auditQueue, "Очередь необработанных действий в системе")
    }

    Container_Boundary(ml, "Контейнер модуля подсказок") {
        Component(mlService, "Сервис подсказок?")
        ComponentDb(mlDB, "Хранилище подсказок?")
        Rel(mlService, mlDB, "")
    }

    Container_Boundary(coreApp, "Контейнер ядра"){
        Component(aaa,"AAA")
        Component(learn,"Обучение")
        Component(users,"Пользователи")
        Component(rooms,"Игровые комнаты")
        Component(content,"Контент книг")
        Component(hintSupplier, "Генераторы подсказок", "")
        Rel(coreApp, hintSupplier, "", $tags="dm")
        Rel(hintSupplier, ml, "", $tags="dm")
        Rel(coreApp, aaa,"")
        Rel(coreApp, content, "")
        Rel(coreApp, learn,"")
        Rel(coreApp, rooms,"")
        Rel(coreApp, users,"")

        Component(bot, "Чат-бот")
        Component(eventHandler, "Обработчик действий при игре")
        Component(generators, "Генераторы объектов")
        Component(heroes,"Редактор персонажей")
        Component(objects, "Объекты в прохождении")

        Rel(coreApp, heroes, "", $tags="player")
        Rel(coreApp, eventHandler, "")
        Rel(coreApp, generators, "", $tags="dm")
        Rel(coreApp, objects, "")

        Rel(generators, objects, "", $tags="dm")
        Rel(heroes, objects, "", $tags="player")

        Rel_D(eventHandler, objects, "")
        Rel_L(eventHandler, eventQueue, "")
        Rel_D(eventQueue, eventHandler, "")
        Rel_L(eventHandler, bot, "")
    }
    Container_Boundary(coreDB, "Контейнер БД") {
        Component(dbBooks,"Контент книг")
        Component(dbObjects,"Объекты в кампании")
        Component(dbChronic, "Хроника событий в кампании")
        Component(dbLearn,"Обучение")
        Component(dbUsers,"Пользователи")
        Component(dbRooms,"Игровые комнаты")
        Component(dbArchive,"Архив кампаний")
        Component(dbAAA,"Записи аудита")
    }
    Rel(rooms, dbRooms, "")
    Rel(users, dbUsers, "")
    Rel(learn, dbLearn, "")
    Rel(rooms, dbArchive, "")
    Rel(aaa, dbAAA, "")
    Rel(aaa, auditQueue, "")
    Rel(auditQueue, aaa, "")
}
Rel_D(cm, gateway, "")
Rel_D(dm, gateway, "")
Rel_D(owner, gateway, "")
Rel_D(player, gateway, "")
Rel_D(table, gateway, "")

Rel_R(gateway, cache, "")
Rel(gateway, coreApp, "")

Rel(objects, dbObjects,  "")
Rel(eventHandler, dbChronic,  "")
Rel(content, dbBooks, "")

Rel(aaa, oauth, "")
Rel(bot, discord, "")

Rel(objects, content, "")

@enduml
