@startuml
left to right direction

actor "Владелец" as UO $UO #blue;line:blue;line.bold;text:blue
actor "Редактор" as UE $UE #maroon;line:maroon;line.bold;text:maroon
actor "Игрок" as UP $UP #orange;line:orange;line.bold;text:orange
actor "Ведущий" as UD $UD #green;line:green;line.bold;text:green

rectangle "Пользователи" as Users {
    usecase "Регистрироваться" as Register
    UP --> Register #orange
    usecase "Аутентифицироваться" as Auth
    UD --> Auth #green
    UE --> Auth #maroon
    UO --> Auth #blue
    UP --> Auth #orange
    usecase "Управлять пользователями" as ManageUsers
    UO --> ManageUsers #blue
    usecase "Выходить из системы" as Logout
    UD --> Logout #green
    UE --> Logout #maroon
    UO --> Logout #blue
    UP --> Logout #orange
}

rectangle "Игровые комнаты/прохождения" as Rooms {
    usecase "Создавать игровую комнату" as CreateRoom
    UD --> CreateRoom #green
    usecase "Редактировать игровую комнату" as EditRoom
    UD --> EditRoom #green
    usecase "Архивировать игровую комнату" as ArchiveRoom
    UD --> ArchiveRoom #green
    usecase "Восстановить игровую комнату" as RestoreRoom
    UD --> RestoreRoom #green
    usecase "Искать игровые комнаты" as SearchRoom
    UP --> SearchRoom #orange
    usecase "Вступать в игровую комнату" as JoinRoom
    UP --> JoinRoom #orange
    usecase "Покидать игровую комнату" as LeaveRoom
    UP --> LeaveRoom #orange
}

rectangle "Обучение" as Education {
    usecase "Проходить обучение" as Learn
    UD --> Learn #green
    UE --> Learn #maroon
    UP --> Learn #orange
    usecase "Редактировать обучение" as EditLearn
    UE --> EditLearn #maroon
}

rectangle "Контент книг, сеттингов, приключений, хоумбрю" as Content {
    usecase "Получать контент" as ReadContent #red
    UE --> ReadContent #maroon
    UP --> ReadContent #orange
    UD --> ReadContent #green
    usecase "Создавать контент" as CreateContent
    UE --> CreateContent #maroon
    usecase "Изменять контент" as EditContent
    UE --> EditContent #maroon
    usecase "Удалять контент" as DeleteContent
    UE --> DeleteContent #maroon
}

rectangle "Состояние прохождения" as Campaigns {
    usecase "Получать состояние объекта" as GetState #red
    UD --> GetState #green
    UP --> GetState #orange
    usecase "Менять состояние объекта" as ChangeState #red
    UD --> ChangeState #green
    UP --> ChangeState #orange
    usecase "Генерировать игровые объекты" as Generate #red
    UD --> Generate #green
    usecase "Создавать персонажа" as CreateChar
    UP --> CreateChar #orange
    usecase "Редактировать персонажа" as EditChar
    UP --> EditChar #orange
    usecase "Импортировать персонажа" as ImportChar
    UP --> ImportChar #orange
    usecase "Экспортировать персонажа" as ExportChar
    UD --> EditChar #green
    UP --> ExportChar #orange
    usecase "Экспортировать прохождение" as ExportHistory
    UD --> ExportHistory #green
}

rectangle "Подсказки" as Hints {
    usecase "Запрашивать подсказки" as AskHint #red
    UD --> AskHint #green
    usecase "Настраивать подсказки" as TuneHint
    UD --> TuneHint #green
}

'remove Hints
'remove Users
'remove Education
'remove Rooms
'remove UO
'remove UE
remove @unlinked
@enduml
